version: "3.9"

services:
  tcpcipher:
    container_name: tcpcipher
    image: luxorlabs/tcpcipher:v2.46.0
    volumes:
      - ./tcpcipher/config.toml:/tcpcipher.toml
    ports:
      - 10500:10000
      - 8383:8383
    command: ./tcpcipher --config tcpcipher.toml
    restart: always
