localaddr = "0.0.0.0:8383"
remoteaddr = "tunnel.luxor88.com:700"
mode = "encrypter"
proxyprotocol = true
encryptionkey = "woVqmgfWfbjlZaRx"

[appconfig.log]
format = "json"
level = "info"

[appconfig.telemetry]
address = "0.0.0.0:10000"
enablePprof = true
enableConfigurationLog = true

[appconfig.telemetry.metrics]
enableMetrics = true
